export const STATUS_SHOW = "STATUS_SHOW";
export const STATUS_HIDE = "STATUS_HIDE";
export const LOAD_COMICS_SUCCESS = "LOAD_COMICS_SUCCESS";
export const UNLOAD_COMICS_SUCCESS = "UNLOAD_COMICS_SUCCESS";
export const TRY_AUTHENTICATE_SUCCESS = "TRY_AUTHENTICATE_SUCCESS";
export const TRY_AUTHENTICATE_ERROR = "TRY_AUTHENTICATE_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT";
